### ISSUE TITLE
Missing file

### ISSUE THREAD

**Issue by JensenGao** [alberto-santini/train-energy-genetic-algorithm#1]
Hello, thank you for your sharing.
When I cmake your code,there something worng in it, it is siad ‘target_link_libraries(tega ${MATH})
target_link_libraries(tega ${JANSSON})’    MATH and  JANSSON are not found. And in your code, you are included the head file "jansson.h" and "inttypes.h",but there are not found. Hope you can supplement files and make it complete.

**Comment by alberto-santini** [comment]
Jansson is an external library. If you don't have inttypes.h you are maybe using an obsolete standard library.

**Comment by alberto-santini** [comment]
Also, notice that the code is a discontinued work-in-progress, so there is not much you can run. At most, I think you can read the source files and see if something is useful for your projects.

**Comment by JensenGao** [comment]
Thank you for your reply, I'll read your code carefully.
